
name: spacejob scraper

on: workflow_dispatch

jobs:
  spacejob:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: make Date thingy
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"

      - name: Build image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false

          tags: spacewatcher
          labels: ${{ steps.meta.outputs.labels }}

      # - uses: docker/build-push-action@v2
      #   with:
      #     tags: test-image:latest
      #     push: false

      - uses: addnab/docker-run-action@v3
        with:
          image: spacewatcher
          run: python3 test_script.py

      - name: view output
        run: |
          ls


      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: spacescrape_${{ steps.date.outputs.date }}
          release_name: spacescrape_${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: |
            results-artifact.txt
 
