
name: spacejob scraper otc accmf

on:
  workflow_dispatch:
    inputs:
      quotes_url:
        description: 'url for quotes'
        required: true
        default: ''

#scrape At the end of every day
# on:
#   schedule:
#    - cron: "0 0 * * *"

jobs:
  spacejob:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: make Date thingy
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"

        #https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false

          tags: spacewatcher
          labels: ${{ steps.meta.outputs.labels }}

      #### container mounts python code at runtime
      #https://github.com/marketplace/actions/docker-run-action
      - uses: addnab/docker-run-action@v3
        with:
          image: spacewatcher
          # options: -w /usr/workspace -v ${{ github.workspace }}:/usr/workspace --env OTC_QUOTES_URL=${{ secrets.OTC_QUOTES_URL }} 
          options: -w /usr/workspace -v ${{ github.workspace }}:/usr/workspace --env OTC_QUOTES_URL=${{ github.event.inputs.quotes_url }}
          run: python3 -m unittest test_script.TestTemplate.test_case_1

      - name: view output
        run: |
          ls
          cat prev_close.txt
          


      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: spacescrape_${{ steps.date.outputs.date }}
      #     release_name: spacescrape_${{ steps.date.outputs.date }}
      #     draft: false
      #     prerelease: false
      #     files: |
      #       result.txt
 
